#yaml基本语法
#k: v:表示一对键值对(k，v之间有空格)
#以空格的缩进来控制层级关系，只要是左对齐的一列数据，都是同一个层级的
#字面量:普通的值(数字，字符串，布尔),且字符串默认不用加上单引号或双引号
#     “”:不会转义字符串里面的特殊字符，特殊字符会作为本身想表达的意思
#      ''：会转义特殊字符，特殊字符最终只是一个普通的字符串数据
#对象，Map(属性和值)(键值对)
#k: v:
#  对象还是k: v的方式,在下一行来写对象的属性和值的关系，注意缩进
#friends:
#       lastName:zhangsan
#        age:20
#行内写法:
#friends: {lastname: zhangsan,age: 18}
#数组(List,Set)
#用-值表示数组中的一个元素
#pets:
#    - cat
#    - dog
#    - pig
#行内写法
#pets: {cat,dog,pig}
server:
  port: 8082
spring:
  profiles:
    active: dev
---

server:
  port: 8083
spring:
  profiles: dev  #指定属于哪个环境
---
server:
  port: 8084
#person:
#       lastName: zhangsan
#       age: 18
#       boss: false
#       birth: 2017/12/12
#       maps: {k1: v1,k2: v2}
#       lists:
#            - lisi
#            - wangwu
#            - zhaoliu
#       dog:
#          name: 小狗
spring:
  profiles: prod
#          age:  2